Build all assets and a release with drone
go-gitea/theme pull request #9
Opened 2016-12-07 09:46 UTC by metalmatze

Pretty straight forward and `.drone.yml` inspired by the one from github.com/go-gitea/gitea. 😄

2016-12-07 13:37 UTC, tboerger requested changes

2016-12-07 13:37 UTC, tboerger commented on .drone.yml
> +    target: /theme/master
Just /theme

2016-12-07 13:37 UTC, tboerger commented on .drone.yml
> +    source: dist/*
You want to create an tar.gz archive and upload only that

2016-12-07 13:38 UTC, metalmatze commented on .drone.yml
> +    source: dist/*
I'll do that right after I get home! 😊

2016-12-07 22:50 UTC, metalmatze commented
Please squash when merging! 😉

2016-12-07 23:02 UTC, tboerger commented on .gitignore
> +/dist/
This is not used anymore

2016-12-07 23:02 UTC, tboerger commented on .drone.yml
> +    image: node
Let's use webhippie/node:latest like we do for golang :)

2016-12-07 23:06 UTC, metalmatze commented on .drone.yml
> +    image: node
https://hub.docker.com/r/webhippie/node/ returns 404? :(

2016-12-07 23:10 UTC, metalmatze commented on .drone.yml
> +    image: node
Furthermore I don't really see much benefit just for the building pipeline. We're not running our app with node. Probably the official one will be updated more frequently? 😊

2016-12-08 05:59 UTC, tboerger commented on .drone.yml
> +    image: node
Oh it's nodejs

2016-12-08 15:51 UTC, tboerger commented
LGTM

2016-12-08 15:51 UTC, tboerger approved these changes

2016-12-08 16:17 UTC, Bwko commented
LGTM

2016-12-08 16:18 UTC, merged